baseurl = "https://brunopacheco1.github.io"
title = "Bruno Pacheco"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

[params]
author = "Bruno Pacheco" 
info = "Senior Software Engineer"
description = "Bruno Pacheco's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/avatar.jpg"
colorScheme = "auto"
customCSS = []
customSCSS = []

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/brunopacheco1"

[[params.social]]
name = "GitLab"
icon = "fa fa-2x fa-gitlab"
weight = 1
url = "https://gitlab.com/brunopacheco1"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/brunopacheco1/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
